version: '3.7'

services:

  mysqldb:
    image: mysql:8.0.31
    restart: always
    environment:
      MYSQL_DATABASE: 'imbus'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'lmao'
      MYSQL_ROOT_PASSWORD: 'lmaoroot'
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - imbus-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      retries: 10
      interval: 3s
      timeout: 30s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://mysqldb:3306/imbus?useSSL=false",
        "spring.datasource.username" : "admin",
        "spring.datasource.password" : "lmao",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    networks:
      - imbus-network

volumes:
  mysql-data:

networks:
  imbus-network:
    name: imbus-network
