version: '3.8'

networks:
  imbus-network:
    external: true
    
services:
  mysqldb:
    image: mysql:8.0.31
    restart: always
    environment:
      MYSQL_DATABASE: 'imbus'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'lmao'
      MYSQL_ROOT_PASSWORD: 'lmaoroot'
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
    networks:
      - imbus-network


  app:
    depends_on:
      - mysqldb
    build: ./backend
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://mysqldb:3306/imbus?useSSL=false",
        "spring.datasource.username" : "admin",
        "spring.datasource.password" : "lmao",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    networks:
      - imbus-network

volumes:
  db:
