import {StyleSheet} from "react-native";

export const input = StyleSheet.create({
    inputContainer: {
        width: '100%',
        backgroundColor: '#fff',
        borderRadius: 100,
        borderColor: '#000',
        borderWidth: 1,
        marginBottom: 10,
        height: 50,
        display: 'flex',
        flexDirection: 'row',
        paddingLeft: 5,
    },
    input: {
        width: '85%',
        padding: 10,
        paddingLeft: 0,
        height: 50,
        fontSize: 16,
    },
    inputShowHide: {
        width: '65%',
        padding: 10,
        paddingLeft: 0,
        height: 50,
        fontSize: 16,
    },
    inputIcon: {
        width: 45,
        padding: 10,
    },
    inputShadowContainer: {
        width: '100%',
        backgroundColor: '#fff',
        borderRadius: 100,
        borderColor: '#000',
        borderWidth: 1,
        marginBottom: 10,
        height: 50,
        display: 'flex',
        flexDirection: 'row',
        paddingLeft: 5,
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 0.32,
        shadowRadius: 5.46,
        elevation: 2,
    },
    inputShadowLargeContainer: {
        width: '100%',
        backgroundColor: '#fff',
        borderRadius: 20,
        borderColor: '#000',
        borderWidth: 1,
        height: 80,
        display: 'flex',
        flexDirection: 'row',
        paddingLeft: 5,
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 0.32,
        shadowRadius: 5.46,
        elevation: 2,
        alignItems: 'flex-start',
    },
    inputNoIcon: {
        width: '100%',
        padding: 10,
        paddingLeft: 0,
        marginLeft: 10,
        height: '100%',
        fontSize: 16,
        textAlignVertical: 'top',
    },
})