package com.blitz.imbus.domain.enums;

import jakarta.persistence.Column;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;

public enum CategoryType {
    ADAPTACIJE,
    ARHITEKTURA,
    BAZENI,
    BOJLERI,
    BRAVARSKI_RADOVI,
    CISCENJE,
    ELEKTROINSTALACIJE,
    FASADE,
    GRIJANJE,
    IZRADA_NAMJESTAJA,
    IZRADA_TROSKOVNIKA,
    KEMIJSKO_CISCENJE,
    KERAMIKA,
    KLIMATIZACIJA,
    KROVOPOKRIVACKI_RADOVI,
    KUCNI_APARATI,
    KUCNI_MAJSTOR,
    METALNE_KONSTRUKCIJE,
    ODVOZ_OTPADAI_RUSENJE,
    PLINSKE_INSTALACIJE,
    PODOVI,
    PROZORI_I_VRATA,
    RESTAURACIJA,
    ROLETE_I_KOMARNICI,
    SELIDBE,
    SIGURNOSNI_SUSTAVI,
    SOBOSLIKARSTVO,
    SOLARNI_PANELI,
    STAKLARSKI_RADOVI,
    SUHOGRADNJA,
    TENDE,
    VODOINSTALACIJE,
    VRT_I_OKUCNICA,
    VELIKI_GRADEVINSKI_RADOVI,
    ZIDARSTVO;
}
