version: '3.3'
services:
  db:
    image: mysql:8.0.31
    restart: always
    environment:
      MYSQL_DATABASE: 'imbus'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'lmao'
      MYSQL_ROOT_PASSWORD: 'lmaoroot'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: